name: build
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Extract Version from gradle.properties
        id: extract_version
        run: echo "VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "moreladders-$VERSION"
          path: "build/libs/moreladders-$VERSION.jar"

      - name: Upload Mod Sources Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "moreladders-$VERSION-sources.jar"
          path: "build/libs/moreladders-$VERSION-sources.jar"
