name: build
on:
  push:
    branches:
      - 1.20.4
      - 1.20.2
    paths-ignore:
      - 'README.md'
      - 'src/main/resources/assets/moreladders/lang/**'
      - '.github/**'
      - 'images/**'
  pull_request:
    branches:
      - 1.20.4
      - 1.20.2
    paths-ignore:
      - 'README.md'
      - 'src/main/resources/assets/moreladders/lang/**'
      - '.github/**'
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Extract Version from gradle.properties
        id: extract_version
        run: echo "VERSION=$(cat gradle.properties | grep mod_version | cut -d'=' -f2 | xargs)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "moreladders-${{ env.VERSION }}"
          path: "build/libs/moreladders-${{ env.VERSION }}.jar"

      - name: Upload Mod Sources Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "moreladders-${{ env.VERSION }}-sources"
          path: "build/libs/moreladders-${{ env.VERSION }}-sources.jar"
